services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_face_tracking
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    command: ["/mediamtx.yml"]
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    ports:
      - "8554:8554"
      - "9999:9999"

  face_tracking:
    build: .
    container_name: face-tracking
    ports:
      - "8000:8000"
    environment:
      OPENCV_FFMPEG_CAPTURE_OPTIONS: "rtsp_transport;tcp|stimeout;5000000"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq_face_tracking:5672/"
      RABBITMQ_EXCHANGE: "faces"
      CAMERA_SOURCE: "rtsp://mediamtx:8554/lecture_{lecture_id}"
      FPS: "15"
      JPEG_QUALITY: "80"
    depends_on:
      - rabbitmq
      - mediamtx
    restart: unless-stopped
