version: "3.8"
services:
  face_tracking_rabbitmq1:
    image: rabbitmq:3-management
    container_name: face-tracking-rabbitmq1
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest